---

- name: Check if "{{ repo.name }}" repo exists
  uri:
    url: https://localhost/pulp/api/v2/repositories/{{ repo.group }}-{{ repo.platform }}{{ repo.platform_version | default('') }}-{{ repo.name }}-{{ repo.tag }}/
    method: GET
    validate_certs: "{{ pulp_repos_validate_certs }}"
    force_basic_auth: yes
    user: "{{ pulp_repos_auth_user }}"
    password: "{{ pulp_repos_auth_user }}"
  register: pulp_repos_delete_check
  failed_when: false

- name: Delete "{{ repo.name }}" repo
  uri:
    url: https://localhost/pulp/api/v2/repositories/{{ repo.group }}-{{ repo.platform }}{{ repo.platform_version | default('') }}-{{ repo.name }}-{{ repo.tag }}/
    method: DELETE
    validate_certs: "{{ pulp_repos_validate_certs }}"
    force_basic_auth: yes
    user: "{{ pulp_repos_auth_user }}"
    password: "{{ pulp_repos_auth_user }}"
    status_code: 202
  register: pulp_repos_deleted
  changed_when: >
    pulp_repos_deleted is defined and
    pulp_repos_deleted.status == 202
  when: pulp_repos_delete_check.status == 200
